// Array of philosophy quotes
const quotes = [
  "Be — don't try to become. – Osho",
  "Love is the goal, life is the journey. – Osho",
  "Be realistic: Plan for a miracle. – Osho",
  "Truth is not something outside to be discovered, it is something inside to be realized. – Osho",
  "Experience life in all possible ways. – Osho",
  "Life begins where fear ends. – Osho",
  "Courage is a love affair with the unknown. – Osho",
  "Don’t choose. Accept life as it is in its totality. – Osho",
  "The greatest freedom is to be free of your own mind. – Osho",
  "The moment you accept yourself, you become beautiful. – Osho",
  "Falling in love, you remain a child; rising in love, you mature. – Osho",
  "If you love a flower, don’t pick it up. – Osho",
  "Friendship is the purest love. – Osho",
  "Creativity is the greatest rebellion in existence. – Osho",
  "Life repeats itself mindlessly unless you become mindful, it will go on repeating like a wheel. – Osho",
  "Don’t seek, don’t search, don’t ask, don’t knock, don’t demand – relax. – Osho",
  "Life is not a problem to be solved: It is a mystery to be lived. – Osho",
  "Don’t be afraid of experience, because the more experience you have, the more mature you become. – Osho",
  "A certain darkness is needed to see the stars. – Osho",
  "Respect your uniqueness, and drop comparison. – Osho",
  "Sadness gives depth. Happiness gives height. – Osho",
  "The real question is not whether life exists after death. The real question is whether you are alive before death. – Osho",
  "To avoid pain, they avoid pleasure. To avoid death, they avoid life. – Osho",
  "Don’t try to force anything. Let life be a deep let-go. – Osho",
  "Truth is not found by reasoning but by dropping reason. – Osho",
  "Tomorrow never comes, it is always today. – Osho",
  "Don’t move the way fear makes you move. Move the way love makes you move. – Osho",
  "You feel good, you feel bad, and these feelings are bubbling from your own unconsciousness. – Osho",
  "Become more and more innocent, less knowledgeable and more childlike. – Osho",
  "Love is the bridge between you and everything. – Osho",
  "Drop the idea of becoming someone, because you are already a masterpiece. – Osho",
  "Never obey anyone’s command unless it is coming from within you. – Osho",
  "Each person comes into this world with a specific destiny. – Osho",
  "Awareness functions almost like magic. – Osho",
  "A man becomes a Buddha the moment he accepts all that life brings with gratitude. – Osho",
  "The moment you bring a little consciousness to your life, love arises. – Osho",
  "Meditation is a surrender; it is not a demand. It is not forcing existence your way. – Osho",
  "Live dangerously. Live joyously. – Osho",
  "Life is a balance between rest and movement. – Osho",
  "Sadness is nothing but the reflection of a certain depth in you. – Osho",
  "The greatest art is to learn how to love and to be loved. – Osho",
  "The truth is not in books, it is not in scriptures, it is in your heart. – Osho",
  "A true lover is not possessive. – Osho",
  "The moment you accept yourself, you open the door to transformation. – Osho",
  "Real love is not an escape from loneliness, it is a communion. – Osho",
  "The moment you start seeing life as non-serious, a playfulness, all the burden on your heart disappears. – Osho",
  "Become so absolutely free that your very existence is an act of rebellion. – Osho",
  "Be like a tree. Let the dead leaves drop. – Osho",
  "You will never be able to live if you are looking for the meaning of life. – Osho",
  "Don’t seek perfection. Life is already perfect in its imperfection. – Osho",
  "Celebrate your life, your being, and let it be a song. – Osho",
  "Only those who are ready to go beyond the mind will find the truth. – Osho",
  "Life has no purpose other than itself. – Osho",
  "Love needs no reason, no logic. Love is the ultimate law of existence. – Osho",
  "Be ordinary, but bring a quality of awareness to your ordinary life. – Osho",
  "Don’t try to understand life. Live it! – Osho",
  "Love is not about possession. Love is about appreciation. – Osho",
  "When you laugh at yourself, you rise above all your complexes. – Osho",
  "In silence, everything becomes clear. – Osho",
  "Die each moment so that you are renewed each moment. – Osho",
  "Freedom is your ultimate destiny, your intrinsic nature. – Osho",
  "To be creative means to be in love with life. – Osho",
  "Meditation brings you to your own center. – Osho",
  "Drop all your masks. Be sincere, be authentic, be yourself. – Osho",
  "When love and meditation are combined, you become divine. – Osho",
  "Man suffers only because he takes seriously what the gods made for fun. – Osho",
  "Don’t make life a problem. Live it, enjoy it, celebrate it. – Osho",
  "Rejoice in the way things are. – Osho",
  "The less people know, the more stubbornly they know it. – Osho",
  "Let your life be an example of love and compassion. – Osho",
  "The greatest courage in life is to face oneself. – Osho",
  "Drop all desires, and just live this moment. – Osho",
  "People who live in fear never truly live. – Osho",
  "Be so totally free that you can sacrifice everything for freedom. – Osho",
  "True happiness arises only when you live in harmony with existence. – Osho",
  "Life is a mystery. The more you know it, the more beautiful it becomes. – Osho",
  "Be fully alive, because that is the only way to know life. – Osho",
  "Truth is always simple, but the mind loves complexity. – Osho",
  "Become a light unto yourself. – Osho",
  "A loving person lives in a loving world. A hostile person lives in a hostile world. – Osho",
  "Trust life. It is always teaching you the right lessons. – Osho",
  "Wherever you are, be there totally. – Osho",
  "Love yourself, because you are the closest person to yourself. – Osho",
  "Don’t fight with your emotions. Accept them, understand them, and let them flow. – Osho",
  "Your aloneness is your freedom. – Osho",
  "Truth is not something you believe in, but something you realize. – Osho",
  "In the present moment, all eternity is contained. – Osho",
  "Don’t expect the world to make you happy. Bring happiness to the world. – Osho",
  "Learn to listen to silence; it has so much to say. – Osho",
  "Surrender to life. Resist nothing. Let life take you where it wants. – Osho",
  "Freedom means the ability to respond in any situation with total awareness. – Osho",
  "Meditation is a flowering of your inner being. – Osho",
  "To live is to be courageous. – Osho",
  "You don’t have to change the world; just change yourself. – Osho",
  "Celebrate yourself and celebrate all of life. – Osho",
  "Without love, life is meaningless. – Osho",
  "In every moment, life is inviting you to live fully. – Osho",
  "Life is not a serious business; it’s a play! – Osho",
  "God is not a judge; he’s a joker. – Osho",
  "Don’t walk; dance your way through life. – Osho",
  "Laughter is the closest thing to the divine. – Osho",
  "Man has made life too serious; existence is laughing at you! – Osho",
  "Even a mosquito is more alive than a man lost in his mind. – Osho",
  "Don’t try to fix the world—it’s already crazy, enjoy the madness. – Osho",
  "Truth is never serious. It is a cosmic giggle. – Osho",
  "If you take life seriously, you miss the joke. – Osho",
  "The divine is more like a clown than a king. – Osho",
  "Life is a game, but only the wise know how to play. – Osho",
  "Religion has no sense of humor, but God does. – Osho",
  "A wise man knows when to dance in the rain and when to sit in the sun. – Osho",
  "Don’t try to understand the mystery of life. It’s like trying to understand a cat. – Osho",
  "Be like a flower: bloom, sway, and let the wind do what it wants. – Osho",
  "When the heart laughs, the universe joins in. – Osho",
  "Enlightenment is realizing there was nothing to worry about in the first place. – Osho",
  "Life is like a mirror: smile at it, and it smiles back. – Osho",
  "Seriousness is a disease; laughter is the medicine. – Osho",
  "The only way to understand God is to laugh with him. – Osho",
  "When you walk, don’t just walk—wiggle a little! – Osho",
  "Even a stone can teach you a cosmic joke, if you’re ready to laugh. – Osho",
  "An intelligent mind dances through contradictions. – Osho",
  "Meditation is not about sitting still; it’s about feeling like you’ve become the universe’s joke. – Osho",
  "If you’re looking for truth, be ready to find it hiding behind a cosmic prank. – Osho",
  "Life is an infinite playground, and you’re the child who forgot how to play. – Osho",
  "God isn’t hiding; he’s just laughing too hard to come out. – Osho",
  "Don’t follow footprints in the sand; the fun is in making your own messy tracks. – Osho",
  "A spiritual seeker without laughter is like tea without sugar. – Osho",
  "The day you laugh at yourself is the day you start being free. – Osho",
  "Enlightenment is a joke, but only the enlightened are in on it. – Osho",
  "Be a fool, but a wise one. – Osho",
  "Truth is not found at the end of the journey; it’s found in tripping along the way. – Osho",
  "Stop being a prisoner of the mind; join the circus of the universe. – Osho",
  "Meditation is learning to enjoy the nonsense of life. – Osho",
  "Laughter is more sacred than a prayer. – Osho",
  "Life is a paradox wrapped in a riddle, dressed as a clown. – Osho",
  "God probably laughs when humans build temples in his name. – Osho",
  "Dance as if nobody’s watching—because they’re probably not. – Osho",
  "Don’t carry your troubles; they’re heavy. Carry flowers instead. – Osho",
  "When life gives you lemons, ask for tequila and salt. – Osho",
  "Every fool has wisdom hidden in his madness. – Osho",
  "Don’t just seek enlightenment; seek funlight. – Osho",
  "Seriousness is a mask for fear; laughter is the face of courage. – Osho",
  "The universe is full of magic if you stop trying to figure it out. – Osho",
  "The mind makes a problem out of everything, even happiness. – Osho",
  "Stop trying to find the meaning of life; you’re already it. – Osho",
  "A master is one who has learned to live with cosmic absurdity. – Osho",
  "Life is like jazz—it’s best when improvised. – Osho",
  "The mind is a beautiful servant but a dangerous master. – Osho",
  "Love is the fragrance of knowing yourself. – Osho",
  "Meditation is the ultimate luxury, because it is the ultimate love affair. – Osho",
  "Wisdom happens when you relax into your existence. – Osho",
  "The more you love yourself, the less you seek approval. – Osho",
  "Life in itself is neutral; we bring meaning to it through our consciousness. – Osho",
  "Everything that happens is a part of your growth, whether you see it or not. – Osho",
  "The real miracle is not walking on water but being in tune with life. – Osho",
  "Be aware of your ego; it disguises itself in many forms. – Osho",
  "Each moment contains the entire universe if you can live it fully. – Osho",
  "To know yourself is the beginning of freedom. – Osho",
  "Fear is not to be fought, but to be understood. – Osho",
  "The greatest journey is the journey within. – Osho",
  "Real peace is not in the absence of conflict but in the presence of awareness. – Osho",
  "Life loves those who live it fully. – Osho",
  "Comparison is the root cause of all unhappiness. – Osho",
  "The more you cling to something, the more it eludes you. – Osho",
  "The mind always wants more; the heart knows when to say enough. – Osho",
  "Silence is not emptiness; it is fullness. – Osho",
  "When you let go of control, life flows naturally. – Osho",
  "Enlightenment is simply understanding the nature of your own mind. – Osho",
  "Love is not an action; it is a state of being. – Osho",
  "When you are content, nothing external can disturb you. – Osho",
  "The moment you realize you are enough, the universe opens up to you. – Osho",
  "Life is a dynamic process; embrace its uncertainty. – Osho",
  "The wise man uses everything for his growth. – Osho",
  "Happiness is not a destination; it is the way. – Osho",
  "To be present is to be in harmony with existence. – Osho",
  "Let your inner light guide your way, not the opinions of others. – Osho",
  "Don’t look for heaven elsewhere; it is here and now. – Osho",
  "Authenticity is the courage to be yourself in a world that expects conformity. – Osho",
  "Pain is inevitable, but suffering is a choice. – Osho",
  "The more you know yourself, the freer you become. – Osho",
  "Gratitude is the key to abundance. – Osho",
  "Forgiveness is the greatest gift you can give to yourself. – Osho",
  "Meditation is the art of listening to the silence within. – Osho",
  "The highest form of intelligence is the ability to observe without judgment. – Osho",
  "The present moment is the only reality; everything else is an illusion. – Osho",
  "The more you trust life, the more life fulfills your trust. – Osho",
  "Don’t be a prisoner of the past. Be the creator of the present. – Osho",
  "Life becomes meaningful when you give it meaning. – Osho",
  "Learn to let go. The more you hold on, the more you suffer. – Osho",
  "Your outer world reflects your inner state. – Osho",
  "Every ending is a new beginning disguised as loss. – Osho",
  "The purpose of life is to live it with awareness and joy. – Osho",
  "Awareness is the light that dispels the darkness of ignorance. – Osho",
  "When you live with awareness, every act becomes a meditation. – Osho",
  "Freedom is not doing whatever you want; it is knowing what is worth doing. – Osho",
  "To find yourself, lose yourself in love. – Osho",
  "Don’t just exist; bloom! Life is too short to be a bud forever. – Osho",
  "The moment you stop searching, the answer finds you. – Osho",
  "Be like the sky—open, vast, and unaffected by passing clouds. – Osho",
  "Laughter is a meditation in motion; let your giggles awaken your soul. – Osho",
  "Don’t climb mountains for the view; dance on them for the fun! – Osho",
  "Meditation is your inner tea party; invite your silence and watch the chaos dissolve. – Osho",
  "Life isn’t a puzzle to be solved; it’s a riddle meant to be enjoyed. – Osho",
  "The more you try to control life, the more it slips through your fingers like sand. – Osho",
  "Stop chasing the sun; be the light you’re looking for. – Osho",
  "Seriousness is like a lock on your heart; laughter is the key. – Osho",
  "The more you laugh, the closer you are to enlightenment. – Osho",
  "Don’t just walk the path; skip, twirl, and make the journey fun. – Osho",
  "Life doesn’t give you lessons; it hands you a joke book, and you decide how to read it. – Osho",
  "Wisdom whispers, but humor shouts! – Osho",
  "Truth isn’t a destination; it’s the silly dance you do along the way. – Osho",
  "Celebrate your mistakes—they’re just life’s way of tickling you. – Osho",
  "Stop worrying about falling; the earth is always there to catch you. – Osho",
  "Life is a painting; don’t stick to one color. Splash the canvas! – Osho",
  "God hides in the little absurdities of life, waiting to be discovered. – Osho",
  "Meditation is less about stillness and more about learning to groove with the chaos. – Osho",
  "The real rebel doesn’t fight; he dances. – Osho",
  "When you stop chasing butterflies, they land on your shoulder. – Osho",
  "Truth doesn’t knock; it sneaks in when you’re not looking. – Osho",
  "Your mind is like a noisy roommate—learn to laugh at its chatter. – Osho",
  "Stop fearing the unknown—it’s just the universe playing hide-and-seek. – Osho",
  "The soul doesn’t grow old; it grows bold. – Osho",
  "Don’t take yourself too seriously; existence certainly doesn’t. – Osho",
  "Meditation is like learning to enjoy your own company—even when you’re weird. – Osho",
  "Love is the only adventure worth embarking on. – Osho",
  "The more you let go, the more life gives you wings. – Osho",
  "Find the cosmic joke in every situation; it’s always there. – Osho",
  "Stop chasing happiness—it’s playing peek-a-boo with you right now. – Osho",
  "Life isn’t a straight line; it’s a loop-de-loop of laughter and tears. – Osho",
  "Truth is a surprise party the universe throws for you. – Osho",
  "Dance in the rain, because waiting for the sun is boring. – Osho",
  "Don’t be afraid of falling apart; that’s how stars are born. – Osho",
  "The ego is a balloon; laughter is the pin. – Osho",
  "When life gives you lemons, don’t just make lemonade—make a whole citrus festival! – Osho",
  "Wisdom isn’t serious; it’s lighthearted and free. – Osho",
  "Celebrate the absurdity of existence; that’s where the magic hides. – Osho",
  "Be so alive that the dead start feeling jealous. – Osho",
  "Every obstacle is just the universe challenging you to a dance-off. – Osho",
  "The heart doesn’t follow rules; it creates its own rhythm. – Osho",
  "Don’t be a seeker; be a finder. – Osho",
  "The secret to happiness? Stop looking for it. – Osho",
  "Life is a comedy for those who think and a tragedy for those who don’t laugh. – Osho",
  "Dive into the mystery, and trust that the ocean will catch you. – Osho",
  "The divine isn’t far—it’s in your next laugh. – Osho",
  "Life isn’t about finding yourself; it’s about creating yourself—and having fun doing it! – Osho",
  "Every laugh is a crack where the light of existence shines through. – Osho",
  "Be like water—soft, flexible, and impossible to hold back. – Osho",
  "The moment you stop worrying about being perfect, you become beautiful. – Osho",
  "Don’t just meditate—marinate in the joy of being alive. – Osho",
  "The stars didn’t ask for permission to shine; neither should you. – Osho",
  "Why be a sheep when you can be a singing, dancing rainbow unicorn? – Osho",
  "Truth is not taught; it is tickled out of you by existence. – Osho",
  "Stop chasing shadows; turn around and face the sun. – Osho",
  "Even your fears are just clouds passing through the vast sky of your being. – Osho",
  "When you smile, the whole universe dances with you. – Osho",
  "Don’t wait for the perfect wave—learn to surf the messy ones. – Osho",
  "Freedom doesn’t come from breaking chains; it comes from realizing they never existed. – Osho",
  "Life is a circus—learn to juggle, and enjoy the show! – Osho",
  "Stop looking for shortcuts; the scenic route is where the magic happens. – Osho",
  "The universe is not serious; it’s a cosmic clown entertaining itself. – Osho",
  "Dive into the unknown; that’s where life hides its treasures. – Osho",
  "Be so present that even time stops to admire you. – Osho",
  "Your heart knows the truth; your mind just complicates it. – Osho",
  "If you stumble, make it part of the dance. – Osho",
  "Even silence has a rhythm if you’re still enough to hear it. – Osho",
  "The journey of self-discovery isn’t a straight path—it’s a spiral staircase of surprises. – Osho",
  "The divine isn’t in the sky; it’s in the sparkle of your eyes. – Osho",
  "Don’t fight the waves of life—learn to float and enjoy the ride. – Osho",
  "Your soul is like a mirror—dust it off, and watch it shine. – Osho",
  "Stop being a tourist in your own life; become the tour guide instead. – Osho",
  "The ego builds walls; love builds bridges. – Osho",
  "Truth is not serious; it’s a belly laugh that shakes your very being. – Osho",
  "Even the chaos of life has a hidden harmony. – Osho",
  "When you realize you are both the dancer and the dance, freedom dawns. – Osho",
  "Don’t follow the herd; carve your own trail through the wilderness. – Osho",
  "Happiness is not a destination; it’s the journey itself. – Osho",
  "When you embrace the absurdity of life, you begin to live. – Osho",
  "The universe speaks in whispers; listen closely. – Osho",
  "If you want peace, stop waging war against yourself. – Osho",
  "Even the darkest night cannot extinguish the light of a single star. – Osho",
  "Every breath is an invitation to fall in love with life again. – Osho",
  "Why wait for permission to live? Life has already said yes to you. – Osho",
  "Meditation isn’t escaping life; it’s diving deeper into it. – Osho",
  "Let go of your worries; they’re like old baggage on a new journey. – Osho",
  "Freedom is not about doing what you want; it’s about being who you are. – Osho",
  "Dance as if the universe itself is your partner. – Osho",
  "Stop chasing rainbows; be the pot of gold you’re searching for. – Osho",
  "Your mind is a prankster; don’t take its jokes too seriously. – Osho",
  "When you laugh, even the stars listen. – Osho",
  "Don’t get stuck in the maze of questions; the answer is in the moment. – Osho",
  "Be wild, be weird, be wonderfully you! – Osho",
  "Truth isn’t far away—it’s sitting quietly, waiting for you to notice. – Osho",
  "When you embrace life’s chaos, you discover its hidden grace. – Osho",
  "The journey to truth begins the moment you stop running from yourself. – Osho",
  "Laughter is a bridge between the mundane and the divine. – Osho",
  "Why fit in when existence itself is a celebration of uniqueness? – Osho",
  "Meditation is the art of coming home to your soul. – Osho",
  "Life is a cosmic drama; learn to laugh at your role. – Osho",
  "Freedom is not in rebellion; it is in acceptance of what is. – Osho",
  "Don’t seek the meaning of life; be the meaning of life. – Osho",
  "The more you align with your heart, the lighter your steps become. – Osho",
  "God is not a person but the silence that holds the universe together. – Osho",
  "Be so open to life that even the wind feels like a gentle embrace. – Osho",
  "The mind creates prisons; love creates wings. – Osho",
  "If existence had a voice, it would be laughter. – Osho",
  "Stop waiting for the perfect moment; every moment is perfection in disguise. – Osho",
  "Truth is a whisper that only the quiet mind can hear. – Osho",
  "Be like the river—flowing, flexible, and always in harmony with its journey. – Osho",
  "Seriousness is the death of joy; let playfulness resurrect your soul. – Osho",
  "When you truly live, every breath becomes a prayer. – Osho",
  "Why fight the current when the river knows its destination? – Osho",
  "Real intelligence is the courage to say, 'I don’t know.' – Osho",
  "Stop chasing enlightenment; it arrives when you stop running. – Osho",
  "Dance, not because you have to, but because the universe moves through you. – Osho",
  "Your heart is a compass; trust it to guide you to your truth. – Osho",
  "The soul doesn’t count time; it counts moments of love. – Osho",
  "Life is a gift; the wrapping is irrelevant. – Osho",
  "Don’t try to figure life out; it’s not a puzzle—it’s a mystery. – Osho",
  "When you surrender, life takes you to the exact place you need to be. – Osho",
  "Even the smallest flower blooms with the same joy as the sun rising. – Osho",
  "Let your fears dissolve in the warmth of self-love. – Osho",
  "When you let go of expectations, the unexpected becomes beautiful. – Osho",
  "Stop trying to control life; it’s not a math equation but a poem. – Osho",
  "Be so still that even time pauses to sit beside you. – Osho",
  "Your laughter is the universe clapping its hands in joy. – Osho",
  "The divine isn’t hiding; it’s dancing in every raindrop and sunbeam. – Osho",
  "Seriousness is the weight of the ego; lightness is the freedom of the soul. – Osho",
  "Don’t carry the past like a burden; let it become the wind beneath your wings. – Osho",
  "The spiritual path is not about becoming; it’s about unbecoming. – Osho",
  "Existence is always ready to surprise you—let yourself be astonished. – Osho",
  "If your soul had a language, it would be silence. – Osho",
  "Learn to dance with life’s chaos; it’s teaching you the steps. – Osho",
  "The moment you stop defining yourself, you start discovering yourself. – Osho",
  "Don’t just hear the music of life—become the melody. – Osho",
  "The greatest prayer is gratitude for the simple act of being. – Osho",
  "Stop measuring life in years; measure it in how deeply you’ve loved. – Osho",
  "Even your imperfections are part of existence’s masterpiece. – Osho",
  "God doesn’t live in temples; he lives in your laughter. – Osho",
  "Truth is a song that can only be heard in stillness. – Osho",
  "The ego wears a crown of seriousness; the soul wears a garland of joy. – Osho",
  "Don’t chase happiness; create it, moment by moment. – Osho",
  "Enlightenment isn’t something you achieve; it’s the realization that nothing is missing. – Osho",
  "Don’t try to light up the world; become the flame that inspires it. – Osho",
  "The spiritual journey begins the moment you stop trying to arrive. – Osho",
  "Why be a drop when you can realize you are the ocean? – Osho",
  "Meditation is not escaping life; it’s diving so deep that you find the truth of it. – Osho",
  "The universe loves a playful heart; that’s where the magic happens. – Osho",
  "Stop searching for love outside yourself; the real treasure is within. – Osho",
  "The ego wants applause; the soul just wants to dance. – Osho",
  "Trust existence; it has already written a beautiful story for you. – Osho",
  "Enlightenment is simply waking up from the dream of who you think you are. – Osho",
  "The divine is not found in faraway places; it’s in your next deep breath. – Osho",
  "Why so serious? Even the stars laugh as they shine. – Osho",
  "Don’t wait for the storm to pass; learn to dance in the rain. – Osho",
  "Let go of your mind, and you’ll find the soul waiting patiently. – Osho",
  "Life is not about reaching a destination; it’s about enjoying the curves of the road. – Osho",
  "Truth isn’t heavy; it’s as light as a feather on the wind. – Osho",
  "Celebrate your existence, for the universe chose to express itself through you. – Osho",
  "Laughter is the shortest distance between two souls. – Osho",
  "Don’t resist life’s flow; it knows the way better than you do. – Osho",
  "Your inner child knows more about the divine than your intellect ever will. – Osho",
  "Stop being a prisoner of your thoughts; become the sky they pass through. – Osho",
  "Every moment is a chance to fall in love with existence all over again. – Osho",
  "Don’t climb the ladder of success; jump off it and find the real joy of being. – Osho",
  "Your soul is like a lotus—blooming beautifully even in muddy waters. – Osho",
  "The mind complicates; the heart simplifies. – Osho",
  "Even silence becomes music when you’re truly at peace. – Osho",
  "Don’t fear the unknown; it’s the playground of the divine. – Osho",
  "The sun rises every day to remind you to shine. – Osho",
  "Meditation isn’t about doing; it’s about undoing. – Osho",
  "The divine doesn’t need temples; it needs your open heart. – Osho",
  "Why carry the weight of the world when existence invites you to fly? – Osho",
  "The moment you laugh at yourself, you break free from your ego. – Osho",
  "Even in chaos, there’s a hidden harmony waiting for you to discover. – Osho",
  "The truth doesn’t argue; it simply exists, like the sun. – Osho",
  "Dance with the unknown; it’s where life’s real beauty hides. – Osho",
  "Don’t chase happiness; it’s already playing hide-and-seek within you. – Osho",
  "When the heart leads, the mind becomes a humble servant. – Osho",
  "Stop looking for the meaning of life; create it with every breath. – Osho",
  "Life isn’t a problem to be solved but a mystery to be celebrated. – Osho",
  "Your soul whispers; your ego shouts. Listen carefully. – Osho",
  "Don’t put limits on yourself; existence doesn’t. – Osho",
  "God is not a being but the infinite love present in everything. – Osho",
  "Truth isn’t far—it’s as close as your own heartbeat. – Osho",
  "Be so light that even gravity cannot hold you back. – Osho",
  "Seriousness is a disease; laughter is the cure. – Osho",
  "You don’t need a map for life; trust the compass of your heart. – Osho",
  "Why struggle to be somebody when being nobody is so freeing? – Osho",
  "The divine is not hidden; it’s just waiting for you to look beyond the obvious. – Osho",
  "Stop fearing death; it’s just another doorway to life. – Osho",
  "The soul is eternal, yet it lives every moment as if it’s brand new. – Osho",
  "Don’t just look at the stars; realize you are made of them. – Osho",
  "Life is a paradox: the moment you stop trying to understand, you begin to see. – Osho",
  "Your laughter is the universe’s way of applauding its own creation. – Osho",
  "Let the heart lead; the mind is just a tool, not the master. – Osho",
  "The divine isn’t found in big things—it hides in the ordinary moments of joy. – Osho",
  "Be less of a thinker and more of a feeler; truth speaks the language of the heart. – Osho",
  "Why walk when life is inviting you to dance? – Osho",
  "Trust existence like a bird trusts the wind under its wings. – Osho",
  "The real revolution happens when you drop all masks and live authentically. – Osho",
  "Meditation is the art of being utterly in love with this moment. – Osho",
  "When you let go of control, life flows like a beautiful melody. – Osho",
  "Stop trying to find the answers; enjoy the questions—they’re part of the game. – Osho",
  "Don’t wait for life to start; it’s already happening. – Osho",
  "Truth is not something you achieve; it’s something you remember. – Osho",
  "Your spirit is infinite; it’s your mind that builds walls. – Osho",
  "Even the smallest flower contains the vastness of the universe. – Osho",
  "Celebrate every sunrise as if the universe painted it just for you. – Osho",
  "Laughter is the bridge that connects your heart to the divine. – Osho",
  "The quieter you become, the louder your soul speaks. – Osho",
  "Life doesn’t follow straight lines; it moves in spirals and circles. – Osho",
  "The moment you drop the idea of perfection, everything becomes perfect. – Osho",
  "Don’t fight the waves of life; learn to surf and enjoy the ocean. – Osho",
  "Existence loves you unconditionally; it’s only your ego that doubts. – Osho",
  "The heart doesn’t speak in words; it speaks in vibrations. – Osho",
  "Why be afraid of falling? It’s just another way of learning to fly. – Osho",
  "Meditation is simply the art of watching yourself with love. – Osho",
  "Stop carrying the baggage of your past; the present moment is weightless. – Osho",
  "The divine isn’t in distant heavens; it’s right here, hidden in plain sight. – Osho",
  "Every breath is a reminder that you are a miracle. – Osho",
  "Don’t wait for joy to find you; create it wherever you are. – Osho",
  "The mind divides; love unites. – Osho",
  "Even your shadow is proof that light exists. – Osho",
  "Stop running after the future; it’s running towards you anyway. – Osho",
  "Life doesn’t need a map; it’s an adventure meant to be explored. – Osho",
  "Truth doesn’t arrive; it awakens. – Osho",
  "Let your spirit be as free as a bird, soaring without boundaries. – Osho",
  "The journey inward is the most thrilling adventure of all. – Osho",
  "The greatest wisdom is knowing when to laugh at yourself. – Osho",
  "The universe is a mirror; smile, and it smiles back. – Osho",
  "Even chaos has its own hidden order. – Osho",
  "Why settle for footprints on the sand when you can leave echoes in the stars? – Osho",
  "Meditation is less about doing and more about undoing. – Osho",
  "Don’t wait for the light; realize you are the light. – Osho",
  "The divine is not an achievement but a remembrance. – Osho",
  "Seriousness is the weight of the ego; joy is the lightness of the soul. – Osho",
  "The moment you stop trying to be someone, you become everything. – Osho",
  "Celebrate every breath as a gift from existence. – Osho",
  "Freedom isn’t a destination; it’s the courage to let go of all cages. – Osho",
];

// Function to get a random quote from the array
function getRandomQuote() {
  const randomIndex = Math.floor(Math.random() * quotes.length);
  return quotes[randomIndex];
}

// Function to display the quote
function displayQuote() {
  const quoteText = getRandomQuote();
  const quoteElement = document.getElementById("quote");
  quoteElement.textContent = quoteText;
}

// Event listener for the button to get a new quote
document
  .getElementById("new-quote-btn")
  .addEventListener("click", displayQuote);

// Display a random quote when the page loads
window.onload = displayQuote;
